import type { EventModel } from './models/event.model';

export const DEMO_EVENT_RECORDS: EventModel[] = [
  {
    id: 'evt-conexao-raro-2026',
    title: 'Conexão Raro Summit 2026',
    shortDescription: 'O encontro de quem transforma negócios e comunidades.',
    description: 'Um dia de conteúdo, relacionamento e novas perspectivas para o ecossistema Raro.',
    eventType: 'PAGO',
    priceCents: 18900,
    startAt: '2026-11-20T12:00:00.000Z',
    endAt: '2026-11-20T22:00:00.000Z',
    capacity: 420,
    status: 'INSCRICOES_ABERTAS',
    modality: 'PRESENCIAL',
    location: 'Centro de Convenções · São Paulo, SP',
    registrationsCount: 318,
    confirmedRegistrationsCount: 284,
    revenueCents: 5367600,
    createdById: 'demo-admin',
    createdAt: '2026-08-18T14:30:00.000Z',
  },
  {
    id: 'evt-reforma-tributaria',
    title: 'Reforma Tributária na prática',
    shortDescription: 'Uma manhã para entender o que muda e como se preparar.',
    description: 'Workshop presencial com especialistas convidados e espaço para perguntas.',
    eventType: 'GRATUITO',
    priceCents: 0,
    startAt: '2026-10-22T12:00:00.000Z',
    endAt: '2026-10-22T16:30:00.000Z',
    capacity: 180,
    status: 'INSCRICOES_ABERTAS',
    modality: 'PRESENCIAL',
    location: 'Raro Hub · Campinas, SP',
    registrationsCount: 143,
    confirmedRegistrationsCount: 143,
    revenueCents: 0,
    createdById: 'demo-admin',
    createdAt: '2026-09-02T11:00:00.000Z',
  },
  {
    id: 'evt-forum-liderancas',
    title: 'Fórum de Lideranças Raro',
    shortDescription: 'Ideias que aproximam pessoas e movem o futuro.',
    description: 'Encontro fechado para convidados e lideranças do ecossistema.',
    eventType: 'PAGO',
    priceCents: 25000,
    startAt: '2026-11-05T13:00:00.000Z',
    endAt: '2026-11-05T21:00:00.000Z',
    capacity: 260,
    status: 'AGENDADO',
    modality: 'PRESENCIAL',
    location: 'Casa Raro · São Paulo, SP',
    registrationsCount: 0,
    confirmedRegistrationsCount: 0,
    revenueCents: 0,
    createdById: 'demo-admin',
    createdAt: '2026-09-19T09:15:00.000Z',
  },
  {
    id: 'evt-encontro-online',
    title: 'Encontro de Comunidades',
    shortDescription: 'Uma conversa aberta sobre o que estamos construindo juntos.',
    description: 'Encontro online para participantes das comunidades parceiras.',
    eventType: 'GRATUITO',
    priceCents: 0,
    startAt: '2026-11-10T17:00:00.000Z',
    endAt: '2026-11-10T18:30:00.000Z',
    capacity: null,
    status: 'RASCUNHO',
    modality: 'ONLINE',
    location: 'https://meet.example.com/raro-comunidades',
    registrationsCount: 0,
    confirmedRegistrationsCount: 0,
    revenueCents: 0,
    createdById: 'demo-admin',
    createdAt: '2026-10-02T10:45:00.000Z',
  },
];
