export const ROUTES = {
  home: '/',
  eventDetail: (slug: string) => `/eventos/${slug}`,
  eventCheckout: (slug: string, registrationId: string) => `/eventos/${slug}/inscricao/${registrationId}`,
  registrationStatus: (code: string) => `/inscricao/${code}`,
  certificateValidation: (code: string) => `/certificados/${code}`,
  participantArea: '/minha-area',
  adminLogin: '/admin/entrar',
  adminDashboard: '/admin',
  adminEvents: '/admin/eventos',
  adminEventForm: (id?: string) => (id ? `/admin/eventos/${id}` : '/admin/eventos/novo'),
  adminEventDetail: (id: string) => `/admin/eventos/${id}/detalhe`,
  adminRegistrations: '/admin/inscricoes',
  adminPayments: '/admin/pagamentos',
  adminCoupons: '/admin/cupons',
  adminCheckin: '/admin/check-in',
  adminReports: '/admin/relatorios',
  adminUsers: '/admin/usuarios',
  adminAudit: '/admin/auditoria',
} as const;
