export type CreateEventInputDto = {
  title: string;
  summary: string;
  description: string;
  imageUrl?: string | null;
  startDate: string;
  endDate: string;
  startTime: string;
  endTime: string;
  isOnline: boolean;
  onlineUrl?: string | null;
  venueName?: string | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  capacity: number;
  registrationStart: string;
  registrationEnd: string;
  responsibleName: string;
  responsibleEmail?: string | null;
  workloadHours: number;
  type: string;
  certificateEnabled?: boolean;
  certificateText?: string | null;
  certificateRequiresAttendance?: boolean;
  waitlistEnabled?: boolean;
  waitlistAutoPromote?: boolean;
  seatReservationMinutes?: number;
  maxInstallments?: number;
  allowPix?: boolean;
  allowBoleto?: boolean;
  allowCreditCard?: boolean;
  minInstallmentCents?: number;
  formFields?: Array<{
    fieldKey?: string;
    label: string;
    description?: string | null;
    fieldType: string;
    isRequired?: boolean;
    orderIndex?: number;
    options?: string[];
    placeholder?: string | null;
  }>;
  actorUserId: string;
  actorName: string;
  ip?: string | null;
};
